apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: elephant

resources:
  - namespace.yaml
  - postgres/
  - opensearch/
  - minio/
  - repository/
  - index/
  - user/
  - chrome/

commonLabels:
  app.kubernetes.io/part-of: elephant
