apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: elephant

resources:
  - namespace.yaml
  - postgres.yaml
  - keycloak.yaml
  - minio.yaml
  - opensearch.yaml
  - repository/deployment.yaml
  - elephant-index.yaml
  - elephant-user.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: elephant
